site_name: My Docs
repo_url: https://github.com/yanndrade/ru-ufc
repo_name: yanndrade/ru-ufc
edit_uri: tree/main/docs

theme:
  name: material
  language: pt-BR
  logo: assets/ru-ufc.svg
  favicon: assets/ru-ufc.svg

markdown_extensions:
  - attr_list
  - pymdownx.snippets

extra_css:
  - stylesheets/extra.css

plugins:
  - towncrier

nav:
  - index.md
  - Para Desenvolvedores:
      - CHANGELOG.md
